dynamics_class: "dubins_car"

safety_states: 
  - 0
  - 1
  - 2
safety_controls:
  - 0
  - 1 

obstacles: 
  
  obstacle1:
    type: 'Circle'
    mode: 'Active'
    indices:
      - 0
      - 1
    center: 
      - -3
      - 0
    radius: 1
    padding: .25

  obstacle2:
    type: 'Rectangle'
    mode: 'Active'
    indices:
      - 0
      - 1
    minVal:
      - 7.0
      - 3.0
    maxVal:
      - 9.0
      - 5.0
    padding: .5

  obstacle3:
    type: 'Circle'
    mode: 'Service'
    indices:
      - 0
      - 1
    center:
      - -3.0
      - 4.0
    radius: 1
    padding: .25

  obstacle4:
    type: 'Circle'
    mode: 'Update'
    indices:
      - 0
      - 1
    center:
      - 0.0
      - -1.0
    radius: .25
    padding: .25
    updatetime: 5
  
  obstacle5:
    type: 'Circle'
    mode: 'Detection'
    indices:
      - 0
      - 1
    center:
      - 4.0
      - 0.0
    radius: .5
    padding: .25
    detectionradius: 1

boundary:
  padding: 0
  indices:
    - 0
    - 1
  minVal:
    - -5.0
    - -5.0
  maxVal:
    - 10.0
    - 10.0

obstacle_update_rate_hz: 5

state_domain:
  lo: 
    - -5.0
    - -5.0
    - -3.1416
  hi: 
    - 10.0
    - 10.0
    - 3.1416
  resolution:
    - 41
    - 41
    - 41
  periodic_dims: [2]

control_space:
  n_dims: 2
  lo:
    - -0.2
    - 0.1
  hi: 
    - 0.2
    - 0.2

disturbance_space:
  n_dims: 0
  lo: None
  hi: None

actuation_updates: []

disturbance_updates: []
